name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip

      - name: Set git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"

      - name: Install semantic-release
        run: pip install -U python-semantic-release

      - name: Run Semantic-release
        run: semantic-release publish -D commit_author="github-actions <action@github.com>"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
